//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KindCluster) DeepCopyInto(out *KindCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KindCluster.
func (in *KindCluster) DeepCopy() *KindCluster {
	if in == nil {
		return nil
	}
	out := new(KindCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KindCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KindClusterControlPlaneEndpoint) DeepCopyInto(out *KindClusterControlPlaneEndpoint) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KindClusterControlPlaneEndpoint.
func (in *KindClusterControlPlaneEndpoint) DeepCopy() *KindClusterControlPlaneEndpoint {
	if in == nil {
		return nil
	}
	out := new(KindClusterControlPlaneEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KindClusterExtraMount) DeepCopyInto(out *KindClusterExtraMount) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KindClusterExtraMount.
func (in *KindClusterExtraMount) DeepCopy() *KindClusterExtraMount {
	if in == nil {
		return nil
	}
	out := new(KindClusterExtraMount)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KindClusterExtraPortMapping) DeepCopyInto(out *KindClusterExtraPortMapping) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KindClusterExtraPortMapping.
func (in *KindClusterExtraPortMapping) DeepCopy() *KindClusterExtraPortMapping {
	if in == nil {
		return nil
	}
	out := new(KindClusterExtraPortMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KindClusterList) DeepCopyInto(out *KindClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KindCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KindClusterList.
func (in *KindClusterList) DeepCopy() *KindClusterList {
	if in == nil {
		return nil
	}
	out := new(KindClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KindClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KindClusterNetworking) DeepCopyInto(out *KindClusterNetworking) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KindClusterNetworking.
func (in *KindClusterNetworking) DeepCopy() *KindClusterNetworking {
	if in == nil {
		return nil
	}
	out := new(KindClusterNetworking)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KindClusterNode) DeepCopyInto(out *KindClusterNode) {
	*out = *in
	if in.KubeAdmConfigPatches != nil {
		in, out := &in.KubeAdmConfigPatches, &out.KubeAdmConfigPatches
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExtraMounts != nil {
		in, out := &in.ExtraMounts, &out.ExtraMounts
		*out = make([]KindClusterExtraMount, len(*in))
		copy(*out, *in)
	}
	if in.ExtraPortMappings != nil {
		in, out := &in.ExtraPortMappings, &out.ExtraPortMappings
		*out = make([]KindClusterExtraPortMapping, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KindClusterNode.
func (in *KindClusterNode) DeepCopy() *KindClusterNode {
	if in == nil {
		return nil
	}
	out := new(KindClusterNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KindClusterSpec) DeepCopyInto(out *KindClusterSpec) {
	*out = *in
	if in.FeatureGates != nil {
		in, out := &in.FeatureGates, &out.FeatureGates
		*out = make(map[string]bool, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.RuntimeConfig != nil {
		in, out := &in.RuntimeConfig, &out.RuntimeConfig
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	out.Networking = in.Networking
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]KindClusterNode, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.ControlPlaneEndpoint = in.ControlPlaneEndpoint
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KindClusterSpec.
func (in *KindClusterSpec) DeepCopy() *KindClusterSpec {
	if in == nil {
		return nil
	}
	out := new(KindClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KindClusterStatus) DeepCopyInto(out *KindClusterStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KindClusterStatus.
func (in *KindClusterStatus) DeepCopy() *KindClusterStatus {
	if in == nil {
		return nil
	}
	out := new(KindClusterStatus)
	in.DeepCopyInto(out)
	return out
}
