apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: hello-kind
spec:
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: KindCluster
    name: hello-kind
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: KindCluster
metadata:
  name: hello-kind
spec:
  networking:
    apiServerAddress: "controlPlaneEndpoint"
  nodes:
  - role: control-plane
